channels:
- conda-forge
dependencies:
- python=3.11.8
- pip<=24.0
- pip:
  - mlflow==2.15.0
  - cloudpickle==3.0.0
  - numpy==1.26.4
  - psutil==5.9.8
  - scikit-learn==1.5.1
  - scipy==1.13.1
name: mlflow-env
