max-line-length = 100

[tool.pylint.messages_control]
disable = [
    "missing-class-docstring", 
    "missing-function-docstring",
    "invalid-name",
    "too-many-arguments",      
    "too-many-locals"         
