max-line-length = 100

[tool.pylint.messages_control]
disable = [
    "missing-class-docstring", 
    "missing-function-docstring",
    "missing-module-docstring",
    "invalid-name",
    "unused-variable",
    "too-many-arguments", 
    "line-too-long",    
    "too-many-locals",
    "broad-exception-raised",
    "broad-exception-caught" ,
    "missing-timeout" ,
    "inconsistent-return-statements",
    "import-error",
    "reportMissingImports" ]      
