name: CD Pipeline

on:
  push:
    branches:
      - 'main'

jobs:
  data-pipeline:
    runs-on: macos-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install prefect

      - name: Run Prefect flow
        env:
          PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}
        run: |
          prefect login --key ${{ secrets.PREFECT_API_KEY }}
          prefect agent start --work-queue "my-work-queue"

  deploy-webapp:
    runs-on: macos-latest
    needs: data-pipeline
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        env:
          IMAGE_NAME: "your-dockerhub-username/bike-sharing-app"
        run: |
          docker build -t $project-mlops-web:latest .
          docker push $project-mlops-web:latest

      - name: Deploy to server
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_KEY: ${{ secrets.SERVER_KEY }}
        run: |
          scp -i $SERVER_KEY docker-compose.yml $SERVER_USER@$SERVER_HOST:~/app/
          ssh -i $SERVER_KEY $SERVER_USER@$SERVER_HOST 'cd ~/app && docker-compose pull && docker-compose up -d'

