name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev

      - name: Run Unit tests
        run: pipenv run pytest
        working-directory: ./tests/unit-test  # Adjust if necessary

      - name: List directory contents for debugging
        run: ls -R
        working-directory: ./tests/unit-test  # Ensure this is the correct directory

      - name: Lint
        run: pipenv run pylint --recursive=y src
        working-directory: .  # Assuming 'src' is in the root directory

      - name: Integration Test
        run: pipenv run pytest
        working-directory: ./tests/integration-test  # Adjust if necessary
