name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies from requirements.txt
        run: |
          if [ -f requirements.txt ]; then
            python -m pip install --upgrade pip
            pip install -r requirements.txt
          fi

      - name: Install pipenv and dependencies
        run: |
          python -m pip install --upgrade pip pipenv
          if [ -f Pipfile ]; then
            pipenv install --dev --skip-lock
          fi

      - name: Run Unit tests
        run: |
          if [ -f Pipfile ]; then
            pipenv run pytest
          fi
        working-directory: tests/unit-tests

      - name: Lint
        run: |
          if [ -f Pipfile ]; then
            pipenv run pylint --recursive=y src
          fi
        working-directory: .
