name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies from requirements.txt
        if: exists('requirements.txt')
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install pipenv and dependencies
        if: exists('Pipfile')
        run: |
          python -m pip install --upgrade pip pipenv
          pipenv install --dev --skip-lock

      - name: Run Unit tests
        run: pipenv run pytest
        working-directory: tests/unit-test
        if: exists('Pipfile')

      - name: Lint
        run: pipenv run pylint --recursive=y src
        working-directory: .
        if: exists('Pipfile')
