name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Build and start Docker container
        run: |
          docker-compose up -d  # Adjust this based on your Docker setup
          # Add a delay if needed to allow the container to fully start
          sleep 10

      - name: Run pytest
        run: |
          pytest tests

      - name: Format with Black
        run: |
          pip install black
          black --check project-mlops

      - name: Lint with pylint
        run: |
          pip install pylint
          pylint src
