name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies from requirements.txt if it exists
      run: |
        if [ -f requirements.txt ]; then
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        fi

    - name: Analyzing the code with pylint
      run: |
        if [ -f Pipfile ]; then
          pipenv run pylint $(git ls-files '*.py')
        else
          pylint $(git ls-files '*.py')
        fi
